apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: medisupply
type: Opaque
stringData:
  POSTGRES_USER: __POSTGRES_USER__
  POSTGRES_PASSWORD: __POSTGRES_PASSWORD__
  POSTGRES_DB: users_db
  DATABASE_URL: postgresql://__POSTGRES_USER__:__POSTGRES_PASSWORD__@postgres-service:5432/users_db
