apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: medisupply
type: Opaque
stringData:
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  POSTGRES_DB: users_db
  DATABASE_URL: postgresql://user:password@postgres-service:5432/users_db
