version: "3.9"

services:
  # Servicio de base de datos PostgreSQL
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: pedidos_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pedidos-net

  # Servicio de Redis para buffer y cache
  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - pedidos-net

  # Servicio de la aplicación FastAPI
  pedidos-service:
    build: .
    container_name: pedidos-service
    depends_on:
      - postgres-db
      - redis
    environment:
      DATABASE_URL: postgresql://admin:admin123@postgres-db:5432/pedidos_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8000:8000"
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
    restart: always
    networks:
      - pedidos-net

# Definición de volúmenes persistentes
volumes:
  postgres_data:

# Definición explícita de la red
networks:
  pedidos-net:
    driver: bridge
