apiVersion: v1
kind: Service
metadata:
  name: supplier-service
  namespace: medisupply
  labels:
    app: supplier-service
    service: supplier-service
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: supplier-service
