apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: medisupply
  labels:
    app: client-service
    service: client-service
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: client-service

