apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: client-service-hpa
  namespace: medisupply
  labels:
    app: client-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: client-service-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70  # Escala cuando CPU > 70%
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # Esperar 5 min antes de bajar
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 30   # Escalar rápido
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 1
        periodSeconds: 30

