apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: medisupply
type: Opaque
stringData:
  SECRET_KEY: "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  DATABASE_URL: "postgresql://user:password@postgres-service:5432/users_db"
